### ISSUE TITLE
Sample config files?

### ISSUE THREAD

**Issue by emcniece** [duhio/docker-compose-usenet#1]
Hey, nice work on the stack. All of these services volume out a config directory, any plans on sharing some example configs?

**Comment by stevewm** [comment]
Thanks, appreciate the feedback. 

No plans to supply example configs for services at the moment, in part because I don't want to dictate configuration to users beyond the structure of the stack. 

Additionally, having a set of example configs would likely result in users being lazy and not changing the API keys to unique ones. Ideally we'd be able to supply a file location for API keys on per-service basis, allowing the use of Docker secrets - but I don't have much desire to submit a PR to each project to enable that.

**Comment by emcniece** [comment]
Makes sense, thank you. Secrets would indeed be nice. These stacks populate the config directory with config files if the files don't exist, so that makes it easy to modify.

I ask primarily with Traefik in mind as I am having a hard time getting the `[acme]` config to work properly. It either `fatal`s out with an unknown entrypoint message, or it redirects endlessly and eats up 16GB RAM in 30 seconds. 

There is a catch (and possibly something that warrants a README update) - if individual files are volumed in, and the files don't already exist on the host, Docker will create directories with these names instead of files. This causes Traefik to have a hissy fit.

```yml
  traefik:
    image: traefik:latest
    ...
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik/acme.json:/acme.json
      - ${CONFIG}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${CONFIG}/traefik/.htpasswd:/etc/traefik/.htpasswd:ro
```

For example, if `traefik/acme.json` does not exist on the host, Docker creates `traefik/acme.json/` (a directory) instead of a file. The easy solution is to ensure that these files exist on the host before starting this container.

This brings me to my current problem of trying to configure Traefik - I have created `traefik.toml` and am trying to populate it using various web examples, but I either get a `fatal` or an endless redirect loop and massive memory leak.

More questions:

1. Would you be willing to share a cleaned copy of `traefik.toml` from your setup?
1. Are you attached to Traefik?
1. I'm a co-author of https://github.com/CausticLab/rgon-proxy which we wrote to be a simpler Nginx reverse proxy option - would you be interested in seeing a PR to swap Traefik for Rgon?
