### ISSUE TITLE
SABnzbd Download Directory

### ISSUE THREAD

**Issue by m7ke** [duhio/docker-compose-usenet#12]
I had an issue with sabnzbd downloading files into {CONFIG}/sabnzbd/Downloads directory by default. I had to manually change the download folders in sabnzbd settings as it showed:

**Default Base Folder:** /config

Here's the sabnzbd part of my docker compose:
```
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DOWNLOAD}/incomplete:/incomplete-downloads
      - ${DOWNLOAD}/watch:/watch
    environment:
      - PGID
      - PUID
      - TZ
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
```

I was able to select the _downloads_ and _incomplete-downloads_ folders in sabnzbd settings which resulted in files being downloaded to the correct directories.

I removed the traefik options as I'm using Caddy for reverse proxy/authentication for my domain.
